# Generated by Django 3.2.2 on 2021-05-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfinal',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'самовывоз'), ('delivery', 'доставка')], default='orders_final', max_length=64),
        ),
        migrations.AlterField(
            model_name='orderfinal',
            name='address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='orderfinal',
            name='delivery_dt',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderfinal',
            name='delivery_time_from',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderfinal',
            name='delivery_time_to',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderfinal',
            name='extra_info',
            field=models.TextField(blank=True),
        ),
    ]
