# Generated by Django 3.2.2 on 2021-05-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210520_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfinal',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'самовывоз'), ('delivery', 'доставка')], default='pickup', max_length=64),
        ),
    ]
