# Generated by Django 3.2 on 2021-04-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210413_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ref',
            field=models.CharField(default=123, max_length=64),
            preserve_default=False,
        ),
    ]
