# Generated by Django 3.2 on 2021-04-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='ref',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
